[package]
name = "Hw1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
if-addrs = "0.12.0"
local-ip-address = "0.6.1"
